---- MODULE Actors ----
\****
\* This file is automatically generated and must not be altered.
\* If you want to change predicates of Actors please change the according
\* *Actor MODULE

EXTENDS EnvironmentActor,
        FactorialStepActor

ActorTypes == {"Environment", "FactorialStep"}

ActorActivities(type) ==
   CASE type = "Environment" -> Environment_Activities
     [] type = "FactorialStep" -> FactorialStep_Activities

ActorOperations(type) ==
   CASE type = "Environment" -> Environment_Operations
     [] type = "FactorialStep" -> FactorialStep_Operations

ActorEvents(type) == ActorActivities(type) \cup ActorOperations(type)

----

PossibleState(type) ==
   CASE type = "Environment" -> Environment_PossibleState
     [] type = "FactorialStep" -> FactorialStep_PossibleState

LOCAL ActorsInvariantTS(type,state) ==
   CASE type = "Environment" -> Environment_Invariant(state)
     [] type = "FactorialStep" -> FactorialStep_Invariant(state)

ActorsInvariant ==
   \A type \in ActorTypes :
      \/ \A id \in ActiveActorIDsByType(type) :
         ActorsInvariantTS(type,StateOf(id))

PossibleNewMessages ==
   Environment_PossibleNewMessages \cup
   FactorialStep_PossibleNewMessages

PossibleNewActors ==
   Environment_PossibleNewActors \cup
   FactorialStep_PossibleNewActors

----

InitPredicate(type,state) ==
   CASE type = "Environment" -> Environment_InitPredicate(state)
     [] type = "FactorialStep" -> FactorialStep_InitPredicate(state)

Acquaintances(id) ==
   CASE TypeOf(id) = "Environment" -> Environment_Acquaintances(StateOf(id))
     [] TypeOf(id) = "FactorialStep" -> FactorialStep_Acquaintances(StateOf(id))

PublicState(id) ==
   CASE TypeOf(id) = "Environment" -> Environment_PublicState(StateOf(id))
     [] TypeOf(id) = "FactorialStep" -> FactorialStep_PublicState(StateOf(id))

----

Event_Condition(kind, type, name, state) ==
   CASE type = "Environment" -> Environment_Event_Condition(kind, name, state)
     [] type = "FactorialStep" -> FactorialStep_Event_Condition(kind, name, state)

Event_Predicate(type, kind, name, id, post, new, out, current) ==
   CASE type = "Environment" ->
               Environment_Event_Predicate(kind, name, id, post, new, out, current)
     [] type = "FactorialStep" ->
               FactorialStep_Event_Predicate(kind, name, id, post, new, out, current)

====
