---- MODULE FactorialStepActor ----
\****
\* This file is automatically generated from the factorial-step.ral

EXTENDS ActorEnvironment

----
(* Variables *)

FactorialStep_PossibleState ==
   [initialized : BoolType,
    factor : NatType,
    requester : RefType,
    child : RefType,
    done : BoolType]

FactorialStep_PossibleNewActors ==
   [type : {"FactorialStep"},
    state : FactorialStep_PossibleState,
    id : FreeIDs]

FactorialStep_Invariant(state) ==
   /\ state \in FactorialStep_PossibleState
   /\ \/ state.initialized
      \/ \neg state.initialized

----
(* Init Predicate *)

FactorialStep_InitPredicate(state) ==
   /\ state.initialized = FALSE
   /\ state.factor > 0
   /\ state.done = FALSE

----
(* Acquaintances *)

FactorialStep_Acquaintances(state) == {} \* TODO

----
(* Public State *)

FactorialStep_PublicState(state) == TRUE \* TODO

----
(* Activities *)

FactorialStep_Activities ==
   {"init1", "init2"}

LOCAL FactorialStep_ActivityInit1_Condition(state) ==
   /\ \neg state.initialized
   /\ state.factor = 1

LOCAL FactorialStep_ActivityInit1_Predicate(id, post, new, out, pre) ==
   /\ new = {}
   /\ out = {[name |-> "result",
              destination |-> pre.requester,
              body |-> [value |-> 1],
              amount |-> 1]}
   /\ post.initialized = TRUE
   /\ post.factor = pre.factor
   /\ post.child = pre.child
   /\ post.requester = pre.requester
   /\ post.done = TRUE

LOCAL FactorialStep_ActivityInit2_Condition(state) ==
   /\ \neg state.initialized
   /\ state.factor > 1

LOCAL FactorialStep_ActivityInit2_Predicate(id, post, new, out, pre) ==
   /\ new = {[type |-> "FactorialStep",
              id |-> NextFreeID(1),
              state |-> [requester |-> id,
                         factor |-> pre.factor-1,
                         initialized |-> FALSE,
                         child |-> AnyRef,
                         done |-> FALSE] ]}
   /\ out = {}
   /\ post.initialized = TRUE
   /\ post.factor = pre.factor
   /\ post.child = NextFreeID(1)
   /\ post.requester = pre.requester
   /\ post.done = pre.done


LOCAL FactorialStep_Activity_Condition(name, state) ==
   CASE name = "init1" ->
      FactorialStep_ActivityInit1_Condition(state)
     [] name = "init2" ->
      FactorialStep_ActivityInit2_Condition(state)


LOCAL FactorialStep_Activity_Predicate(name, id, post, new, out, pre) ==
   CASE name = "init1" ->
      FactorialStep_ActivityInit1_Predicate(id, post, new, out, pre)
     [] name = "init2" ->
      FactorialStep_ActivityInit2_Predicate(id, post, new, out, pre)


----
(* Messages *)

FactorialStep_PossibleNewMessages ==
   [name : {"result"},
    destination : ActiveActorIDsByType("FactorialStep"), 
    body : [value : NatType],
    amount : {1,2}]

----
(* Operations *)

FactorialStep_Operations ==
   {"result"}

LOCAL FactorialStep_OperationResult_Condition(state) ==
   state.initialized

LOCAL FactorialStep_OperationResult_Predicate(id, post, new, out, pre) ==
   /\ new = {}
   /\ out = {[name |-> "result",
              destination |-> pre.requester,
              body |-> [value |-> (NextMessageBody(id).value * pre.factor)],
              amount |-> 1]}
   /\ post.initialized = pre.initialized
   /\ post.factor = pre.factor
   /\ post.requester = pre.requester
   /\ post.child = pre.child
   /\ post.done = TRUE


LOCAL FactorialStep_Operation_Condition(name, state) ==
   CASE name = "result" ->
      FactorialStep_OperationResult_Condition(state)


LOCAL FactorialStep_Operation_Predicate(name, id, post, new, out, pre) ==
   CASE name = "result" ->
      FactorialStep_OperationResult_Predicate(id, post, new, out, pre)


----

FactorialStep_Event_Condition(kind, name, state) ==
   IF kind = "activity"
   THEN
      FactorialStep_Activity_Condition(name, state)
   ELSE \* kind = "operation"
      FactorialStep_Operation_Condition(name, state)

FactorialStep_Event_Predicate(kind, name, id, post, new, out, pre) ==
   IF kind = "activity"
   THEN
      FactorialStep_Activity_Predicate(name, id, post, new, out, pre)
   ELSE \* kind = "operation"
      /\ name = NextMessageName(id)
      /\ FactorialStep_Operation_Predicate(name, id, post, new, out, pre)

====
